const SB_URL = "https://adsevhtaaqerrumdjqdz.supabase.co";
const SB_KEY = "sb_publishable_VpehK1TR2_aEOt-XgwtKhg_dHx8NAmI";
const supabaseClient = supabase.createClient(SB_URL, SB_KEY);

document.addEventListener('DOMContentLoaded', () => {
    const potato = document.getElementById('potato');
    const sidebar = document.getElementById('sidebar');
    const fileInput = document.getElementById('fileInput');
    const pcField = document.getElementById('pcType');

    // --- HARDWARE SCANNER SIMULATION ---
    const hardwareDatabase = [
        "NVIDIA RTX 4080 | Core i7-13700K",
        "NVIDIA RTX 3070 | Ryzen 7 5800X",
        "GTX 1660 Super | Core i5-11400",
        "AMD RX 6800 XT | Ryzen 9 5900X",
        "Integrated UHD 620 | Core i3-10110U"
    ];

    setTimeout(() => {
        pcField.value = hardwareDatabase[Math.floor(Math.random() * hardwareDatabase.length)];
    }, 1200);

    // --- SIDEBAR NAVIGATION ---
    document.getElementById('toggleSidebar').onclick = function() {
        const closed = sidebar.classList.toggle('closed');
        this.innerText = closed ? "▶" : "◀";
    };

    document.querySelectorAll('.nav-item').forEach(item => {
        item.onclick = () => {
            const page = item.dataset.page;
            document.querySelectorAll('.content-page').forEach(p => p.classList.add('hidden'));
            document.getElementById(`${page}Page`).classList.remove('hidden');
            document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
            item.classList.add('active');
        };
    });

    // --- FILE HANDLING ---
    document.getElementById('dropZone').onclick = () => fileInput.click();
    fileInput.onchange = (e) => {
        if(e.target.files[0]) {
            const file = e.target.files[0];
            document.getElementById('fileLabel').innerHTML = `<strong>${file.name}</strong><br>${(file.size / 1024 / 1024).toFixed(2)} MB LOADED`;
        }
    };

    // --- COMPRESSION ENGINE ---
    document.getElementById('igniteBtn').onclick = () => {
        const file = fileInput.files[0];
        if(!file) return alert("Error: No game file detected in the compression box.");

        // Visual State Shift
        potato.classList.remove('blue-aura');
        potato.classList.add('compressing-red');
        document.getElementById('statusText').innerText = "INJECTING POTATO OPTIMIZATIONS...";
        
        const startTime = Date.now();

        // Simulated Processing Logic
        setTimeout(() => {
            potato.classList.remove('compressing-red');
            potato.classList.add('blue-aura');
            
            const compressionLevel = document.getElementById('compLevel').value;
            const savings = (compressionLevel * 100).toFixed(0);
            
            document.getElementById('statusText').innerText = "SUCCESS: " + savings + "% COMPRESSION REACHED";
            
            // Create a downloadable "Potato Profile"
            const content = `Game: ${file.name}\nOptimization: ${savings}%\nHardware: ${pcField.value}\nGenerated by Hot Potato Compressor.`;
            const blob = new Blob([content], { type: 'text/plain' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `potatofied_${file.name.split('.')[0]}.txt`;
            a.click();
            
            alert("Potatofied profile generated! Apply this to your game directory for optimized FPS.");
        }, 5000);
    };

    // --- AUTH UI ---
    document.getElementById('openSignup').onclick = () => document.getElementById('authModal').classList.remove('hidden');
    document.getElementById('closeModal').onclick = () => document.getElementById('authModal').classList.add('hidden');
});
